# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('currency', models.CharField(choices=[('usd', '$'), ('eur', '€'), ('uah', '₴'), ('rub', '₽')], default='uah', max_length=10, verbose_name='currency')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
            ],
            options={
                'verbose_name_plural': 'services',
                'verbose_name': 'service',
            },
        ),
    ]
