# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-25 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(max_length=5, unique=True, verbose_name='number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('customer_first_name', models.CharField(max_length=100, verbose_name='customer first name')),
                ('customer_last_name', models.CharField(max_length=100, verbose_name='customer last name')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('phone_verification_code', models.CharField(max_length=5, verbose_name='phone verification code')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='is phone verified')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service', verbose_name='service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'orders',
                'verbose_name': 'order',
            },
        ),
    ]
