# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
