# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('returned', 'Returned')], default='unconfirmed', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='price'),
        ),
    ]
