# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-26 08:39
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20181226_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
